server:
  tomcat:
    uri-encoding: UTF-8

spring:
    datasource:
        name: oracloud
        url: jdbc:mysql://127.0.0.1:3306/schedule?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 10
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

rpc:
    dark:
        url: "http://127.0.0.1:18332/"
        username: "ora"
        password: "Oradt!1234"
    ltc:
        url: "http://ELB-TCP-Blockchain-8ce9078d9f50e341.elb.cn-northwest-1.amazonaws.com.cn:9332/"
        username: "ora"
        password: "Oradt!1234"
    btc:
        url: "http://192.168.12.39:8332"
        username: "bitcoinrpc"
        password: "2XA4DuKNCbtZXsBQRRNDEwEY2nM6M4H9Tx5dFjoAVVbK"
    web3j:
        url: "http://52.83.130.131:8545"
